# ╔═╗┌─┐┌┬┐┌─┐┬  ┌─┐┌┬┐┬┌─┐┌┐┌┌─┐
# ║  │ ││││├─┘│  ├┤  │ ││ ││││└─┐
# ╚═╝└─┘┴ ┴┴  ┴─┘└─┘ ┴ ┴└─┘┘└┘└─┘
# Load CLI tool completions.
#
# Tools that auto-generate their PowerShell completions by running the binary
# (e.g. `starship completions powershell`) are CACHED to disk and only
# regenerated when the binary's mtime changes. This avoids spawning a process
# per tool per shell startup, which previously cost ~1.5s.

$completionsDir = Join-Path (Split-Path $PROFILE) "Completions"
$cacheDir = Join-Path $env:XDG_CACHE_HOME "powershell\completions"
if (-not (Test-Path $cacheDir)) {
    New-Item -ItemType Directory -Path $cacheDir -Force | Out-Null
}
function Test-PowerShellScriptText {
    param([string]$Text)

    if ([string]::IsNullOrWhiteSpace($Text)) { return $false }

    $tokens = $null
    $errors = $null
    [System.Management.Automation.Language.Parser]::ParseInput($Text, [ref]$tokens, [ref]$errors) | Out-Null
    return ($errors.Count -eq 0)
}

function Test-PowerShellScriptFile {
    param([string]$Path)

    if (-not (Test-Path $Path)) { return $false }

    $tokens = $null
    $errors = $null
    [System.Management.Automation.Language.Parser]::ParseFile($Path, [ref]$tokens, [ref]$errors) | Out-Null
    return ($errors.Count -eq 0)
}

# Tools whose completions are generated by invoking the binary.
# Cache invalidates when the binary's LastWriteTime is newer than the cache file.
$cacheableCompletions = [ordered]@{
    'arduino-cli' = { & arduino-cli completion powershell }
    chezmoi  = { & chezmoi completion powershell }
    delta    = { & delta --generate-completion powershell }
    deno     = { & deno completions powershell }
    docker   = { & docker completion powershell }
    fd       = { & fd --gen-completions powershell }
    gh       = { & gh completion -s powershell }
    glab     = { & glab completion -s powershell }
    glow     = { & glow completion powershell }
    just     = { & just --completions powershell }
    kubectl  = { & kubectl completion powershell }
    lazygit  = { & lazygit completion powershell }
    procs    = { & procs --gen-completion-out powershell }
    rg       = { & rg --generate complete-powershell }
    rustup   = { & rustup completions powershell }
    scott    = { & scott completion powershell }
    starship = { & starship completions powershell }
    taplo    = { & taplo completions powershell }
    uv       = { & uv generate-shell-completion powershell }
    warp     = { & warp completions }
    wezterm  = { & wezterm shell-completion --shell power-shell }
    xh       = { & xh --generate complete-powershell }
    yq       = { & yq completion powershell }
}

foreach ($tool in $cacheableCompletions.Keys) {
    $cmd = Get-Command $tool -ErrorAction SilentlyContinue
    if (-not $cmd) { continue }

    $cachePath = Join-Path $cacheDir "$tool.ps1"
    $exePath = if ($cmd.Source) { $cmd.Source } else { $cmd.Definition }

    $rebuild = -not (Test-Path $cachePath)
    if ((-not $rebuild) -and $exePath -and (Test-Path $exePath)) {
        $rebuild = (Get-Item $exePath).LastWriteTime -gt (Get-Item $cachePath).LastWriteTime
    }

    if ($rebuild) {
        Write-Verbose "Regenerating completion cache for ${tool}"
        $tmpPath = $null
        try {
            $generated = & $cacheableCompletions[$tool] 2>$null | Out-String
            if (Test-PowerShellScriptText -Text $generated) {
                $tmpPath = Join-Path $cacheDir "$tool.ps1.tmp.$PID"
                Set-Content -Path $tmpPath -Value $generated -Encoding utf8
                Move-Item -Path $tmpPath -Destination $cachePath -Force
            } elseif (-not [string]::IsNullOrWhiteSpace($generated)) {
                Write-Verbose "Generated completion for ${tool} failed PowerShell parse validation; keeping existing cache"
            }
        } catch {
            Write-Verbose "Failed to generate completion for ${tool}: $($_.Exception.Message)"
        } finally {
            if ($tmpPath -and (Test-Path $tmpPath)) {
                Remove-Item -Path $tmpPath -Force -ErrorAction SilentlyContinue
            }
        }
    }

    if (Test-Path $cachePath) {
        if (Test-PowerShellScriptFile -Path $cachePath) {
            try {
                . $cachePath
            } catch {
                Write-Verbose "Skipping completion cache for ${tool}: $($_.Exception.Message)"
            }
        } else {
            Write-Verbose "Removing invalid completion cache for ${tool}: $cachePath"
            Remove-Item -Path $cachePath -Force -ErrorAction SilentlyContinue
        }
    }
}

# Load any remaining hand-written / static completion scripts.
# The cacheable ones above are skipped to avoid double-loading.
if (Test-Path $completionsDir) {
    Get-ChildItem "$completionsDir\*.ps1" -ErrorAction SilentlyContinue |
        Where-Object { -not $cacheableCompletions.Contains($_.BaseName) } |
        ForEach-Object {
            Write-Verbose "Loading completion: $($_.Name)"
            . $_.FullName
        }
}

# vim: ts=2 sts=2 sw=2 et
