# ╔═╗┌─┐┌┬┐┌─┐┬  ┌─┐┌┬┐┬┌─┐┌┐┌┌─┐
# ║  │ ││││├─┘│  ├┤  │ ││ ││││└─┐
# ╚═╝└─┘┴ ┴┴  ┴─┘└─┘ ┴ ┴└─┘┘└┘└─┘
# Load CLI tool completions.
#
# Tools that auto-generate their PowerShell completions by running the binary
# (e.g. `starship completions powershell`) are CACHED to disk and only
# regenerated when the binary's mtime changes. This avoids spawning a process
# per tool per shell startup, which previously cost ~1.5s.

$completionsDir = Join-Path (Split-Path $PROFILE) "Completions"
$cacheDir = Join-Path $env:XDG_CACHE_HOME "powershell\completions"
if (-not (Test-Path $cacheDir)) {
    New-Item -ItemType Directory -Path $cacheDir -Force | Out-Null
}

# Tools whose completions are generated by invoking the binary.
# Cache invalidates when the binary's LastWriteTime is newer than the cache file.
$cacheableCompletions = [ordered]@{
    chezmoi  = { & chezmoi completion powershell }
    delta    = { & delta --generate-completion powershell }
    docker   = { & docker completion powershell }
    fd       = { & fd --gen-completions powershell }
    gh       = { & gh completion -s powershell }
    glab     = { & glab completion -s powershell }
    kubectl  = { & kubectl completion powershell }
    rg       = { & rg --generate complete-powershell }
    rustup   = { & rustup completions powershell }
    scott    = { & scott completion powershell }
    starship = { & starship completions powershell }
    warp     = { & warp completions }
    wezterm  = { & wezterm shell-completion --shell power-shell }
}

foreach ($tool in $cacheableCompletions.Keys) {
    $cmd = Get-Command $tool -ErrorAction SilentlyContinue
    if (-not $cmd) { continue }

    $cachePath = Join-Path $cacheDir "$tool.ps1"
    $exePath = if ($cmd.Source) { $cmd.Source } else { $cmd.Definition }

    $rebuild = -not (Test-Path $cachePath)
    if ((-not $rebuild) -and $exePath -and (Test-Path $exePath)) {
        $rebuild = (Get-Item $exePath).LastWriteTime -gt (Get-Item $cachePath).LastWriteTime
    }

    if ($rebuild) {
        Write-Verbose "Regenerating completion cache for ${tool}"
        try {
            $generated = & $cacheableCompletions[$tool] 2>$null | Out-String
            if (-not [string]::IsNullOrWhiteSpace($generated)) {
                Set-Content -Path $cachePath -Value $generated -Encoding utf8
            }
        } catch {
            Write-Verbose "Failed to generate completion for ${tool}: $($_.Exception.Message)"
        }
    }

    if (Test-Path $cachePath) {
        . $cachePath
    }
}

# Load any remaining hand-written / static completion scripts.
# The cacheable ones above are skipped to avoid double-loading.
if (Test-Path $completionsDir) {
    Get-ChildItem "$completionsDir\*.ps1" -ErrorAction SilentlyContinue |
        Where-Object { -not $cacheableCompletions.Contains($_.BaseName) } |
        ForEach-Object {
            Write-Verbose "Loading completion: $($_.Name)"
            . $_.FullName
        }
}

# vim: ts=2 sts=2 sw=2 et
